### ISSUE TITLE
TypeError: Cannot set property 'v' of undefined excel builder

### ISSUE THREAD

**Issue by maheshsetti** [chuanyi/msexcel-builder#35]
TypeError: Cannot set property 'v' of undefined excel builder
 return this.data[row][col].v = this.book.ss.str2id('' + str);
path:
node_modules/msexcel-builder-colorfix/lib/msexcel-builder.js:337

node_modules/msexcel-builder-colorfix/lib/msexcel-builder.js:337
      return this.data[row][col].v = this.book.ss.str2id('' + str);
                           ^
TypeError: Cannot read property '1' of undefined
this error i am getting rarely, i dont know why it is coming?

**Comment by maheshsetti** [comment]
Solution of this error is we have to mention rows and colomuns when we are creating excel. i didnt mention enough rows :P

**Comment by dahngeek** [comment]
Same happened to me, it was that i was setting the column in the row, and  viceversa... Just in case someone else happens to do the same :)

**Comment by maheshsetti** [comment]
yup, i have found this before and i fixed.

**Comment by bestconsultant** [comment]
No wonder we all have this error if we follow the doc where it says

```
// Create a new worksheet with 10 columns and 12 rows 
  var sheet1 = workbook.createSheet('sheet1', 10, 12);
```

And actually this is 10 rows and 12 columns.

**Comment by amsimaganti** [comment]
Followed above and struggled a lot in finding the Issue, but what document says is correct it should be of  the same **col,rows** order. I missed to add **+1** to the number of **rows**  in addition to the data array length  for column headings

**Comment by Espartac0** [comment]
Could someone tell me where do i have to mention rows and columns?
