### ISSUE TITLE
Empty folders created

### ISSUE THREAD

**Issue by mjasnikovs** [chuanyi/msexcel-builder#53]
After creating xlsx in destination folder, there is created some random numbered folders.
Like  "1220132", there shod be option to remove them automatically.

**Comment by kholiavko-roman** [comment]
I have this issue too, anytime when I run my script, it creates new empty folder

**Comment by ged-ward** [comment]
me too. solutions or options ?

**Comment by mjasnikovs** [comment]
This library is not maintained anymore. I would advice to find another solution.
