### ISSUE TITLE
worksheet.save is creating columns with data mismatch whenever a sheet has more than 25+ columns or 1000+ rows eventhough sheet.set has correct data

### ISSUE THREAD

**Issue by SundareswaranP** [chuanyi/msexcel-builder#84]

**Comment by protobi-pieter** [comment]
@sundareswaranP 

Thanks for the alert.  Can you provide a test case? Or try this with branch `https://github.com/protobi/msexcel-builder`, which is a fork of this repo which we actively maintain.   

I just added a test case https://github.com/protobi/msexcel-builder/blob/master/test/issue-84.js.  At first glance this appears to correctly set cells past 25 columns and 1000 rows.

<img width="579" alt="image" src="https://user-images.githubusercontent.com/10464727/211247355-af0d04e3-0ddf-41bd-91ca-a7ea1dffd258.png">

**Comment by SundareswaranP** [comment]
Hi @pietersv 

Thanks for responding. My excel has 970 rows and 40 columns. 

Each cell can have either one of the below values

1) YES
2) NO
3) BLANK SPACE(Empty cell)

Columns from 20 to 40 are mostly having incorrect data. Empty cells are filled with either YES or NO.

sheet1.set(colIndex, rowIndex, cellData); // Able to set proper and legit value but after save getting incorrect data.

Below is the code I am using
		
		workbook.save(function (ok) {
            if (!!ok) {
                workbook.cancel();
            }
            else {
                var fs = require('fs');
                var readStream = fs.createReadStream(filePath);
                defer.resolve(readStream);
                fs.unlinkSync(filePath);
            }
        });
		
		
		
Also, tried below code as well but still issue persists.
		
		workbook.generate(function (err, jszip) {
            if (err)
                throw err;
            else {
                var buffer = jszip.generate({ type: "nodebuffer" })
                require('fs').writeFile(filePath, buffer, function (err) {
                    console.log('Done');
                })
            }
        });

**Comment by protobi-pieter** [comment]
@SundareswaranP Can you write a short program that generates a workbook replicating the issue?  E.g. like lines 20-57 of this one  https://github.com/protobi/msexcel-builder/blob/master/test/issue-84.js.  (You can paste the code here as a comment in this issue rather than adding a new file in the test directory and submitting pull request )

**Comment by SundareswaranP** [comment]
@pietersv  I have replaced the library 'msexcel-builder' with 'msexcel-builder-extended' and now I am able to get correct data in the excel. Thanks for the support!
